*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZCA_API_V001....................................*
FORM GET_DATA_ZCA_API_V001.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCA_API_T001 WHERE
(VIM_WHERETAB) .
    CLEAR ZCA_API_V001 .
ZCA_API_V001-MANDT =
ZCA_API_T001-MANDT .
ZCA_API_V001-API_ID =
ZCA_API_T001-API_ID .
ZCA_API_V001-NAME =
ZCA_API_T001-NAME .
ZCA_API_V001-BASE_URL =
ZCA_API_T001-BASE_URL .
<VIM_TOTAL_STRUC> = ZCA_API_V001.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCA_API_V001 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCA_API_V001.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCA_API_V001-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCA_API_T001 WHERE
  API_ID = ZCA_API_V001-API_ID .
    IF SY-SUBRC = 0.
    DELETE ZCA_API_T001 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCA_API_T001 WHERE
  API_ID = ZCA_API_V001-API_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCA_API_T001.
    ENDIF.
ZCA_API_T001-MANDT =
ZCA_API_V001-MANDT .
ZCA_API_T001-API_ID =
ZCA_API_V001-API_ID .
ZCA_API_T001-NAME =
ZCA_API_V001-NAME .
ZCA_API_T001-BASE_URL =
ZCA_API_V001-BASE_URL .
    IF SY-SUBRC = 0.
    UPDATE ZCA_API_T001 ##WARN_OK.
    ELSE.
    INSERT ZCA_API_T001 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCA_API_V001-UPD_FLAG,
STATUS_ZCA_API_V001-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCA_API_V001.
  SELECT SINGLE * FROM ZCA_API_T001 WHERE
API_ID = ZCA_API_V001-API_ID .
ZCA_API_V001-MANDT =
ZCA_API_T001-MANDT .
ZCA_API_V001-API_ID =
ZCA_API_T001-API_ID .
ZCA_API_V001-NAME =
ZCA_API_T001-NAME .
ZCA_API_V001-BASE_URL =
ZCA_API_T001-BASE_URL .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCA_API_V001 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCA_API_V001-API_ID TO
ZCA_API_T001-API_ID .
MOVE ZCA_API_V001-MANDT TO
ZCA_API_T001-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCA_API_T001'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCA_API_T001 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCA_API_T001'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZCA_API_V002....................................*
FORM GET_DATA_ZCA_API_V002.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCA_API_T002 WHERE
(VIM_WHERETAB) .
    CLEAR ZCA_API_V002 .
ZCA_API_V002-MANDT =
ZCA_API_T002-MANDT .
ZCA_API_V002-API_ID =
ZCA_API_T002-API_ID .
ZCA_API_V002-ENDPOINT_ID =
ZCA_API_T002-ENDPOINT_ID .
ZCA_API_V002-ENDPOINT_NAME =
ZCA_API_T002-ENDPOINT_NAME .
ZCA_API_V002-ENDPOINT_URL =
ZCA_API_T002-ENDPOINT_URL .
<VIM_TOTAL_STRUC> = ZCA_API_V002.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCA_API_V002 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCA_API_V002.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCA_API_V002-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCA_API_T002 WHERE
  API_ID = ZCA_API_V002-API_ID AND
  ENDPOINT_ID = ZCA_API_V002-ENDPOINT_ID .
    IF SY-SUBRC = 0.
    DELETE ZCA_API_T002 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCA_API_T002 WHERE
  API_ID = ZCA_API_V002-API_ID AND
  ENDPOINT_ID = ZCA_API_V002-ENDPOINT_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCA_API_T002.
    ENDIF.
ZCA_API_T002-MANDT =
ZCA_API_V002-MANDT .
ZCA_API_T002-API_ID =
ZCA_API_V002-API_ID .
ZCA_API_T002-ENDPOINT_ID =
ZCA_API_V002-ENDPOINT_ID .
ZCA_API_T002-ENDPOINT_NAME =
ZCA_API_V002-ENDPOINT_NAME .
ZCA_API_T002-ENDPOINT_URL =
ZCA_API_V002-ENDPOINT_URL .
    IF SY-SUBRC = 0.
    UPDATE ZCA_API_T002 ##WARN_OK.
    ELSE.
    INSERT ZCA_API_T002 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCA_API_V002-UPD_FLAG,
STATUS_ZCA_API_V002-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCA_API_V002.
  SELECT SINGLE * FROM ZCA_API_T002 WHERE
API_ID = ZCA_API_V002-API_ID AND
ENDPOINT_ID = ZCA_API_V002-ENDPOINT_ID .
ZCA_API_V002-MANDT =
ZCA_API_T002-MANDT .
ZCA_API_V002-API_ID =
ZCA_API_T002-API_ID .
ZCA_API_V002-ENDPOINT_ID =
ZCA_API_T002-ENDPOINT_ID .
ZCA_API_V002-ENDPOINT_NAME =
ZCA_API_T002-ENDPOINT_NAME .
ZCA_API_V002-ENDPOINT_URL =
ZCA_API_T002-ENDPOINT_URL .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCA_API_V002 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCA_API_V002-API_ID TO
ZCA_API_T002-API_ID .
MOVE ZCA_API_V002-ENDPOINT_ID TO
ZCA_API_T002-ENDPOINT_ID .
MOVE ZCA_API_V002-MANDT TO
ZCA_API_T002-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCA_API_T002'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCA_API_T002 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCA_API_T002'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZCA_API_V003....................................*
FORM GET_DATA_ZCA_API_V003.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCA_API_T003 WHERE
(VIM_WHERETAB) .
    CLEAR ZCA_API_V003 .
ZCA_API_V003-MANDT =
ZCA_API_T003-MANDT .
ZCA_API_V003-API_ID =
ZCA_API_T003-API_ID .
ZCA_API_V003-ENDPOINT_ID =
ZCA_API_T003-ENDPOINT_ID .
ZCA_API_V003-SERVICE_ID =
ZCA_API_T003-SERVICE_ID .
ZCA_API_V003-SERVICE_PATH =
ZCA_API_T003-SERVICE_PATH .
ZCA_API_V003-SERVICE_TYPE =
ZCA_API_T003-SERVICE_TYPE .
ZCA_API_V003-REQUIRED_BODY =
ZCA_API_T003-REQUIRED_BODY .
ZCA_API_V003-TOKEN_SERVICE =
ZCA_API_T003-TOKEN_SERVICE .
<VIM_TOTAL_STRUC> = ZCA_API_V003.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCA_API_V003 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCA_API_V003.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCA_API_V003-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCA_API_T003 WHERE
  API_ID = ZCA_API_V003-API_ID AND
  ENDPOINT_ID = ZCA_API_V003-ENDPOINT_ID AND
  SERVICE_ID = ZCA_API_V003-SERVICE_ID .
    IF SY-SUBRC = 0.
    DELETE ZCA_API_T003 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCA_API_T003 WHERE
  API_ID = ZCA_API_V003-API_ID AND
  ENDPOINT_ID = ZCA_API_V003-ENDPOINT_ID AND
  SERVICE_ID = ZCA_API_V003-SERVICE_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCA_API_T003.
    ENDIF.
ZCA_API_T003-MANDT =
ZCA_API_V003-MANDT .
ZCA_API_T003-API_ID =
ZCA_API_V003-API_ID .
ZCA_API_T003-ENDPOINT_ID =
ZCA_API_V003-ENDPOINT_ID .
ZCA_API_T003-SERVICE_ID =
ZCA_API_V003-SERVICE_ID .
ZCA_API_T003-SERVICE_PATH =
ZCA_API_V003-SERVICE_PATH .
ZCA_API_T003-SERVICE_TYPE =
ZCA_API_V003-SERVICE_TYPE .
ZCA_API_T003-REQUIRED_BODY =
ZCA_API_V003-REQUIRED_BODY .
ZCA_API_T003-TOKEN_SERVICE =
ZCA_API_V003-TOKEN_SERVICE .
    IF SY-SUBRC = 0.
    UPDATE ZCA_API_T003 ##WARN_OK.
    ELSE.
    INSERT ZCA_API_T003 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCA_API_V003-UPD_FLAG,
STATUS_ZCA_API_V003-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCA_API_V003.
  SELECT SINGLE * FROM ZCA_API_T003 WHERE
API_ID = ZCA_API_V003-API_ID AND
ENDPOINT_ID = ZCA_API_V003-ENDPOINT_ID AND
SERVICE_ID = ZCA_API_V003-SERVICE_ID .
ZCA_API_V003-MANDT =
ZCA_API_T003-MANDT .
ZCA_API_V003-API_ID =
ZCA_API_T003-API_ID .
ZCA_API_V003-ENDPOINT_ID =
ZCA_API_T003-ENDPOINT_ID .
ZCA_API_V003-SERVICE_ID =
ZCA_API_T003-SERVICE_ID .
ZCA_API_V003-SERVICE_PATH =
ZCA_API_T003-SERVICE_PATH .
ZCA_API_V003-SERVICE_TYPE =
ZCA_API_T003-SERVICE_TYPE .
ZCA_API_V003-REQUIRED_BODY =
ZCA_API_T003-REQUIRED_BODY .
ZCA_API_V003-TOKEN_SERVICE =
ZCA_API_T003-TOKEN_SERVICE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCA_API_V003 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCA_API_V003-API_ID TO
ZCA_API_T003-API_ID .
MOVE ZCA_API_V003-ENDPOINT_ID TO
ZCA_API_T003-ENDPOINT_ID .
MOVE ZCA_API_V003-SERVICE_ID TO
ZCA_API_T003-SERVICE_ID .
MOVE ZCA_API_V003-MANDT TO
ZCA_API_T003-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCA_API_T003'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCA_API_T003 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCA_API_T003'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZCA_API_V005....................................*
FORM GET_DATA_ZCA_API_V005.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCA_API_T005 WHERE
(VIM_WHERETAB) .
    CLEAR ZCA_API_V005 .
ZCA_API_V005-MANDT =
ZCA_API_T005-MANDT .
ZCA_API_V005-API_ID =
ZCA_API_T005-API_ID .
ZCA_API_V005-ENDPOINT_ID =
ZCA_API_T005-ENDPOINT_ID .
ZCA_API_V005-SERVICE_ID =
ZCA_API_T005-SERVICE_ID .
ZCA_API_V005-PARAMETER_ID =
ZCA_API_T005-PARAMETER_ID .
ZCA_API_V005-PARAMETER_NAME =
ZCA_API_T005-PARAMETER_NAME .
ZCA_API_V005-REQUIRED =
ZCA_API_T005-REQUIRED .
ZCA_API_V005-VALUE =
ZCA_API_T005-VALUE .
<VIM_TOTAL_STRUC> = ZCA_API_V005.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCA_API_V005 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCA_API_V005.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCA_API_V005-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCA_API_T005 WHERE
  API_ID = ZCA_API_V005-API_ID AND
  ENDPOINT_ID = ZCA_API_V005-ENDPOINT_ID AND
  SERVICE_ID = ZCA_API_V005-SERVICE_ID AND
  PARAMETER_ID = ZCA_API_V005-PARAMETER_ID .
    IF SY-SUBRC = 0.
    DELETE ZCA_API_T005 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCA_API_T005 WHERE
  API_ID = ZCA_API_V005-API_ID AND
  ENDPOINT_ID = ZCA_API_V005-ENDPOINT_ID AND
  SERVICE_ID = ZCA_API_V005-SERVICE_ID AND
  PARAMETER_ID = ZCA_API_V005-PARAMETER_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCA_API_T005.
    ENDIF.
ZCA_API_T005-MANDT =
ZCA_API_V005-MANDT .
ZCA_API_T005-API_ID =
ZCA_API_V005-API_ID .
ZCA_API_T005-ENDPOINT_ID =
ZCA_API_V005-ENDPOINT_ID .
ZCA_API_T005-SERVICE_ID =
ZCA_API_V005-SERVICE_ID .
ZCA_API_T005-PARAMETER_ID =
ZCA_API_V005-PARAMETER_ID .
ZCA_API_T005-PARAMETER_NAME =
ZCA_API_V005-PARAMETER_NAME .
ZCA_API_T005-REQUIRED =
ZCA_API_V005-REQUIRED .
ZCA_API_T005-VALUE =
ZCA_API_V005-VALUE .
    IF SY-SUBRC = 0.
    UPDATE ZCA_API_T005 ##WARN_OK.
    ELSE.
    INSERT ZCA_API_T005 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCA_API_V005-UPD_FLAG,
STATUS_ZCA_API_V005-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCA_API_V005.
  SELECT SINGLE * FROM ZCA_API_T005 WHERE
API_ID = ZCA_API_V005-API_ID AND
ENDPOINT_ID = ZCA_API_V005-ENDPOINT_ID AND
SERVICE_ID = ZCA_API_V005-SERVICE_ID AND
PARAMETER_ID = ZCA_API_V005-PARAMETER_ID .
ZCA_API_V005-MANDT =
ZCA_API_T005-MANDT .
ZCA_API_V005-API_ID =
ZCA_API_T005-API_ID .
ZCA_API_V005-ENDPOINT_ID =
ZCA_API_T005-ENDPOINT_ID .
ZCA_API_V005-SERVICE_ID =
ZCA_API_T005-SERVICE_ID .
ZCA_API_V005-PARAMETER_ID =
ZCA_API_T005-PARAMETER_ID .
ZCA_API_V005-PARAMETER_NAME =
ZCA_API_T005-PARAMETER_NAME .
ZCA_API_V005-REQUIRED =
ZCA_API_T005-REQUIRED .
ZCA_API_V005-VALUE =
ZCA_API_T005-VALUE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCA_API_V005 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCA_API_V005-API_ID TO
ZCA_API_T005-API_ID .
MOVE ZCA_API_V005-ENDPOINT_ID TO
ZCA_API_T005-ENDPOINT_ID .
MOVE ZCA_API_V005-SERVICE_ID TO
ZCA_API_T005-SERVICE_ID .
MOVE ZCA_API_V005-PARAMETER_ID TO
ZCA_API_T005-PARAMETER_ID .
MOVE ZCA_API_V005-MANDT TO
ZCA_API_T005-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCA_API_T005'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCA_API_T005 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCA_API_T005'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZCA_API_V006....................................*
FORM GET_DATA_ZCA_API_V006.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZCA_API_T006 WHERE
(VIM_WHERETAB) .
    CLEAR ZCA_API_V006 .
ZCA_API_V006-MANDT =
ZCA_API_T006-MANDT .
ZCA_API_V006-API_ID =
ZCA_API_T006-API_ID .
ZCA_API_V006-ENDPOINT_ID =
ZCA_API_T006-ENDPOINT_ID .
ZCA_API_V006-SERVICE_ID =
ZCA_API_T006-SERVICE_ID .
ZCA_API_V006-HEADER_ID =
ZCA_API_T006-HEADER_ID .
ZCA_API_V006-HEADER_NAME =
ZCA_API_T006-HEADER_NAME .
ZCA_API_V006-REQUIRED =
ZCA_API_T006-REQUIRED .
ZCA_API_V006-VALUE =
ZCA_API_T006-VALUE .
<VIM_TOTAL_STRUC> = ZCA_API_V006.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZCA_API_V006 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZCA_API_V006.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZCA_API_V006-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCA_API_T006 WHERE
  API_ID = ZCA_API_V006-API_ID AND
  ENDPOINT_ID = ZCA_API_V006-ENDPOINT_ID AND
  SERVICE_ID = ZCA_API_V006-SERVICE_ID AND
  HEADER_ID = ZCA_API_V006-HEADER_ID .
    IF SY-SUBRC = 0.
    DELETE ZCA_API_T006 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCA_API_T006 WHERE
  API_ID = ZCA_API_V006-API_ID AND
  ENDPOINT_ID = ZCA_API_V006-ENDPOINT_ID AND
  SERVICE_ID = ZCA_API_V006-SERVICE_ID AND
  HEADER_ID = ZCA_API_V006-HEADER_ID .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCA_API_T006.
    ENDIF.
ZCA_API_T006-MANDT =
ZCA_API_V006-MANDT .
ZCA_API_T006-API_ID =
ZCA_API_V006-API_ID .
ZCA_API_T006-ENDPOINT_ID =
ZCA_API_V006-ENDPOINT_ID .
ZCA_API_T006-SERVICE_ID =
ZCA_API_V006-SERVICE_ID .
ZCA_API_T006-HEADER_ID =
ZCA_API_V006-HEADER_ID .
ZCA_API_T006-HEADER_NAME =
ZCA_API_V006-HEADER_NAME .
ZCA_API_T006-REQUIRED =
ZCA_API_V006-REQUIRED .
ZCA_API_T006-VALUE =
ZCA_API_V006-VALUE .
    IF SY-SUBRC = 0.
    UPDATE ZCA_API_T006 ##WARN_OK.
    ELSE.
    INSERT ZCA_API_T006 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZCA_API_V006-UPD_FLAG,
STATUS_ZCA_API_V006-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZCA_API_V006.
  SELECT SINGLE * FROM ZCA_API_T006 WHERE
API_ID = ZCA_API_V006-API_ID AND
ENDPOINT_ID = ZCA_API_V006-ENDPOINT_ID AND
SERVICE_ID = ZCA_API_V006-SERVICE_ID AND
HEADER_ID = ZCA_API_V006-HEADER_ID .
ZCA_API_V006-MANDT =
ZCA_API_T006-MANDT .
ZCA_API_V006-API_ID =
ZCA_API_T006-API_ID .
ZCA_API_V006-ENDPOINT_ID =
ZCA_API_T006-ENDPOINT_ID .
ZCA_API_V006-SERVICE_ID =
ZCA_API_T006-SERVICE_ID .
ZCA_API_V006-HEADER_ID =
ZCA_API_T006-HEADER_ID .
ZCA_API_V006-HEADER_NAME =
ZCA_API_T006-HEADER_NAME .
ZCA_API_V006-REQUIRED =
ZCA_API_T006-REQUIRED .
ZCA_API_V006-VALUE =
ZCA_API_T006-VALUE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZCA_API_V006 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZCA_API_V006-API_ID TO
ZCA_API_T006-API_ID .
MOVE ZCA_API_V006-ENDPOINT_ID TO
ZCA_API_T006-ENDPOINT_ID .
MOVE ZCA_API_V006-SERVICE_ID TO
ZCA_API_T006-SERVICE_ID .
MOVE ZCA_API_V006-HEADER_ID TO
ZCA_API_T006-HEADER_ID .
MOVE ZCA_API_V006-MANDT TO
ZCA_API_T006-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCA_API_T006'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCA_API_T006 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCA_API_T006'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
